"""Add black list table to bann tokens

Revision ID: d91e66478d9c
Revises: e9c27d41226f
Create Date: 2024-09-04 11:58:02.216200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91e66478d9c'
down_revision: Union[str, None] = 'e9c27d41226f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
